import {
  PublicKey,
  TransactionInstruction,
  SystemProgram,
} from '@solana/web3.js';
import { HYDENTITY_PROGRAM_ID } from '../constants';
import { getNameVaultPda, getVaultAuthorityPda, getPrivacyPolicyPda } from '../utils/pda';

/**
 * Build instruction to initialize a new vault for an SNS name
 * 
 * @param owner - The owner of the SNS name (signer)
 * @param snsNameAccount - The SNS name account public key
 * @returns TransactionInstruction
 */
export function buildInitializeVaultInstruction(
  owner: PublicKey,
  snsNameAccount: PublicKey
): TransactionInstruction {
  const [vault] = getNameVaultPda(snsNameAccount);
  const [vaultAuthority] = getVaultAuthorityPda(snsNameAccount);
  const [policy] = getPrivacyPolicyPda(snsNameAccount);

  // Instruction discriminator for "initialize_vault"
  // Generated by Anchor: hash("global:initialize_vault")[0..8]
  const discriminator = Buffer.from([
    0x30, 0x2d, 0x28, 0xb8, 0xe6, 0xf8, 0x4e, 0x97
  ]);

  const data = discriminator;

  const keys = [
    { pubkey: owner, isSigner: true, isWritable: true },
    { pubkey: snsNameAccount, isSigner: false, isWritable: false },
    { pubkey: vault, isSigner: false, isWritable: true },
    { pubkey: vaultAuthority, isSigner: false, isWritable: true },
    { pubkey: policy, isSigner: false, isWritable: true },
    { pubkey: SystemProgram.programId, isSigner: false, isWritable: false },
  ];

  return new TransactionInstruction({
    keys,
    programId: HYDENTITY_PROGRAM_ID,
    data,
  });
}

/**
 * Build instruction to withdraw SOL directly from vault (emergency)
 * 
 * @param owner - The vault owner (signer)
 * @param snsNameAccount - The SNS name account public key
 * @param destination - The destination for the withdrawal
 * @param amount - Amount to withdraw in lamports
 * @returns TransactionInstruction
 */
export function buildWithdrawDirectSolInstruction(
  owner: PublicKey,
  snsNameAccount: PublicKey,
  destination: PublicKey,
  amount: bigint
): TransactionInstruction {
  const [vault] = getNameVaultPda(snsNameAccount);
  const [vaultAuthority] = getVaultAuthorityPda(snsNameAccount);

  // Instruction discriminator for "withdraw_direct"
  const discriminator = Buffer.from([
    0x5b, 0x67, 0x0e, 0x88, 0x1d, 0x86, 0x7a, 0x2c
  ]);

  // Encode amount as u64 little-endian
  const amountBuffer = Buffer.alloc(8);
  amountBuffer.writeBigUInt64LE(amount);

  // Encode mint as Option<Pubkey> (None = 0)
  const mintBuffer = Buffer.from([0]); // None

  const data = Buffer.concat([discriminator, amountBuffer, mintBuffer]);

  // Token program ID
  const TOKEN_PROGRAM_ID = new PublicKey('TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA');

  const keys = [
    { pubkey: owner, isSigner: true, isWritable: true },
    { pubkey: snsNameAccount, isSigner: false, isWritable: false },
    { pubkey: vault, isSigner: false, isWritable: true },
    { pubkey: vaultAuthority, isSigner: false, isWritable: false },
    { pubkey: destination, isSigner: false, isWritable: true },
    // Optional token accounts (not provided for SOL)
    { pubkey: TOKEN_PROGRAM_ID, isSigner: false, isWritable: false },
    { pubkey: SystemProgram.programId, isSigner: false, isWritable: false },
  ];

  return new TransactionInstruction({
    keys,
    programId: HYDENTITY_PROGRAM_ID,
    data,
  });
}

/**
 * Build instruction to withdraw SPL tokens directly from vault (emergency)
 * 
 * @param owner - The vault owner (signer)
 * @param snsNameAccount - The SNS name account public key
 * @param destination - The destination wallet
 * @param vaultTokenAccount - The vault's token account
 * @param destinationTokenAccount - The destination's token account
 * @param mint - The token mint
 * @param amount - Amount to withdraw
 * @returns TransactionInstruction
 */
export function buildWithdrawDirectSplInstruction(
  owner: PublicKey,
  snsNameAccount: PublicKey,
  destination: PublicKey,
  vaultTokenAccount: PublicKey,
  destinationTokenAccount: PublicKey,
  mint: PublicKey,
  amount: bigint
): TransactionInstruction {
  const [vault] = getNameVaultPda(snsNameAccount);
  const [vaultAuthority] = getVaultAuthorityPda(snsNameAccount);

  // Instruction discriminator for "withdraw_direct"
  const discriminator = Buffer.from([
    0x5b, 0x67, 0x0e, 0x88, 0x1d, 0x86, 0x7a, 0x2c
  ]);

  // Encode amount as u64 little-endian
  const amountBuffer = Buffer.alloc(8);
  amountBuffer.writeBigUInt64LE(amount);

  // Encode mint as Option<Pubkey> (Some = 1 + pubkey)
  const mintBuffer = Buffer.concat([
    Buffer.from([1]), // Some
    mint.toBuffer(),
  ]);

  const data = Buffer.concat([discriminator, amountBuffer, mintBuffer]);

  const TOKEN_PROGRAM_ID = new PublicKey('TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA');

  const keys = [
    { pubkey: owner, isSigner: true, isWritable: true },
    { pubkey: snsNameAccount, isSigner: false, isWritable: false },
    { pubkey: vault, isSigner: false, isWritable: true },
    { pubkey: vaultAuthority, isSigner: false, isWritable: false },
    { pubkey: destination, isSigner: false, isWritable: true },
    { pubkey: vaultTokenAccount, isSigner: false, isWritable: true },
    { pubkey: destinationTokenAccount, isSigner: false, isWritable: true },
    { pubkey: TOKEN_PROGRAM_ID, isSigner: false, isWritable: false },
    { pubkey: SystemProgram.programId, isSigner: false, isWritable: false },
  ];

  return new TransactionInstruction({
    keys,
    programId: HYDENTITY_PROGRAM_ID,
    data,
  });
}

