use anchor_lang::prelude::*;
use arcium_anchor::prelude::*;

pub mod constants;
pub mod errors;
pub mod instructions;
pub mod state;
pub mod events;

use instructions::*;

declare_id!("46mwRQo4f6sLy9cigZdVJgdEpeEVc6jLRG1H241Uk9GY");

#[arcium_program]
pub mod hydentity {
    use super::*;

    /// Initialize a new vault for an SNS name
    pub fn initialize_vault(ctx: Context<InitializeVault>) -> Result<()> {
        instructions::initialize_vault::handler(ctx)
    }

    /// Update the privacy policy for a vault
    pub fn update_policy(ctx: Context<UpdatePolicy>, params: UpdatePolicyParams) -> Result<()> {
        instructions::update_policy::handler(ctx, params)
    }

    /// Deposit vault funds into Umbra mixer pool
    pub fn deposit_to_umbra(
        ctx: Context<DepositToUmbra>,
        amount: u64,
        mint: Option<Pubkey>,
    ) -> Result<()> {
        instructions::deposit_to_umbra::handler(ctx, amount, mint)
    }

    /// Emergency direct withdrawal (bypasses privacy)
    pub fn withdraw_direct(
        ctx: Context<WithdrawDirect>,
        amount: u64,
        mint: Option<Pubkey>,
    ) -> Result<()> {
        instructions::withdraw_direct::handler(ctx, amount, mint)
    }

    /// Add a delegate with time-bounded execution permissions
    pub fn add_delegate(
        ctx: Context<AddDelegate>,
        expires_at: i64,
        permissions: u8,
    ) -> Result<()> {
        instructions::add_delegate::handler(ctx, expires_at, permissions)
    }

    /// Revoke delegate permissions
    pub fn revoke_delegate(ctx: Context<RevokeDelegate>) -> Result<()> {
        instructions::revoke_delegate::handler(ctx)
    }

    /// Mark domain as transferred to vault authority
    /// 
    /// Called after the user transfers their SNS domain ownership to the vault authority
    /// using the Bonfida SDK. This verifies the transfer and updates vault state.
    pub fn mark_domain_transferred(ctx: Context<MarkDomainTransferred>) -> Result<()> {
        instructions::mark_domain_transferred::handler(ctx)
    }

    /// Reclaim domain ownership from the vault
    /// 
    /// Transfers SNS domain ownership from the vault authority PDA back to 
    /// a specified destination address. Only the vault owner can execute this.
    pub fn reclaim_domain(ctx: Context<ReclaimDomain>) -> Result<()> {
        instructions::reclaim_domain::handler(ctx)
    }

    /// Store private vault configuration via Arcium MPC
    /// 
    /// This instruction receives encrypted vault configuration from the user
    /// and queues an Arcium computation to validate and store it. The configuration
    /// includes destination wallets and privacy settings that will be used for
    /// withdrawal execution.
    pub fn store_private_config(
        ctx: Context<StorePrivateConfig>,
        computation_offset: u64,
        encrypted_data: [u8; 512],
        nonce: [u8; 16],
        pub_key: [u8; 32],
        nonce_u128: u128,
    ) -> Result<()> {
        instructions::store_private_config::handler(
            ctx,
            computation_offset,
            encrypted_data,
            nonce,
            pub_key,
            nonce_u128,
        )
    }

    /// Request a withdrawal with MPC-generated plan
    /// 
    /// This instruction initiates a withdrawal from the vault. The actual
    /// withdrawal plan (destinations, amounts, timing) is generated by the
    /// MPC cluster using the user's encrypted configuration.
    pub fn request_withdrawal(
        ctx: Context<RequestWithdrawal>,
        computation_offset: u64,
        amount: u64,
        user_entropy: [u8; 32],
        entropy_timestamp: i64,
        entropy_signature: [u8; 64],
        arcis_pubkey: [u8; 32],
        encryption_nonce: u128,
    ) -> Result<()> {
        instructions::request_withdrawal::handler(
            ctx,
            computation_offset,
            amount,
            user_entropy,
            entropy_timestamp,
            entropy_signature,
            arcis_pubkey,
            encryption_nonce,
        )
    }

    /// Initialize computation definition for store_private_config
    /// 
    /// This must be called once before using the store_private_config instruction.
    /// Sets up the MPC environment for storing encrypted vault configurations.
    pub fn init_store_private_config_comp_def(
        ctx: Context<InitStorePrivateConfigCompDef>,
    ) -> Result<()> {
        instructions::store_private_config::init_store_private_config_comp_def(ctx)
    }

    /// Initialize computation definition for generate_withdrawal_plan
    /// 
    /// This must be called once before using the request_withdrawal instruction.
    /// Sets up the MPC environment for generating encrypted withdrawal plans.
    pub fn init_generate_plan_comp_def(
        ctx: Context<InitGeneratePlanCompDef>,
    ) -> Result<()> {
        instructions::request_withdrawal::init_generate_plan_comp_def(ctx)
    }
}

