//! Shared types for Hydentity encrypted instructions
//! 
//! These types are used across multiple encrypted instructions and define
//! the core data structures for private vault configuration.

use arcis_imports::*;

/// Maximum number of destination wallets per vault
pub const MAX_DESTINATIONS: usize = 5;

/// Maximum number of splits per withdrawal
pub const MAX_SPLITS: usize = 10;

/// Minimum delay between splits (60 seconds = 1 minute)
pub const MIN_DELAY_FLOOR_SECONDS: u32 = 60;

/// Maximum delay between splits (7 days)
pub const MAX_DELAY_CEILING_SECONDS: u32 = 604800;

/// Private vault configuration - stored encrypted on-chain
/// 
/// This struct contains all the sensitive information about where
/// funds should be sent when withdrawing from the vault. It is
/// encrypted using Rescue cipher with a shared secret between
/// the user and MXE, ensuring only the MPC cluster can decrypt it.
#[derive(Clone, Copy, PartialEq)]
pub struct PrivateVaultConfig {
    /// Configuration version for upgrade compatibility
    pub version: u8,
    
    /// Destination wallet public keys (padded to fixed size)
    /// Each destination is a 32-byte Solana public key
    /// Unused slots are filled with zeros
    pub destinations: [[u8; 32]; MAX_DESTINATIONS],
    
    /// Number of active destinations (1-5)
    /// Only the first `destination_count` entries in `destinations` are valid
    pub destination_count: u8,
    
    /// Minimum number of splits per withdrawal
    pub min_splits: u8,
    
    /// Maximum number of splits per withdrawal
    pub max_splits: u8,
    
    /// Minimum delay between splits (in seconds)
    pub min_delay_seconds: u32,
    
    /// Maximum delay between splits (in seconds)
    pub max_delay_seconds: u32,
    
    /// Whether to automatically trigger withdrawals
    pub auto_withdraw_enabled: bool,
    
    /// Minimum vault balance to trigger auto-withdrawal (lamports)
    pub auto_withdraw_threshold: u64,
    
    /// Owner's public key for verification
    pub owner_pubkey: [u8; 32],
    
    /// Unix timestamp when config was created
    pub created_at: i64,
    
    /// Unix timestamp of last update
    pub updated_at: i64,
    
    /// Whether to route withdrawals through Privacy Cash
    /// When enabled, withdrawals go through Privacy Cash pool instead of Arcium splits
    pub use_privacy_cash: bool,
    
    /// Reserved space for future fields
    pub _reserved: [u8; 31],
}

impl Default for PrivateVaultConfig {
    fn default() -> Self {
        Self {
            version: 1,
            destinations: [[0u8; 32]; MAX_DESTINATIONS],
            destination_count: 0,
            min_splits: 2,
            max_splits: 5,
            min_delay_seconds: 300,   // 5 minutes
            max_delay_seconds: 1800,  // 30 minutes
            auto_withdraw_enabled: false,
            auto_withdraw_threshold: 0,
            owner_pubkey: [0u8; 32],
            created_at: 0,
            updated_at: 0,
            use_privacy_cash: false,
            _reserved: [0u8; 31],
        }
    }
}

/// Result of storing private configuration
#[derive(Clone, Copy)]
pub struct ConfigStorageResult {
    /// Whether storage was successful
    pub success: bool,
    
    /// Hash of the stored config (for verification)
    pub config_hash: [u8; 32],
    
    /// Slot at which config was stored
    pub stored_at_slot: u64,
}

/// A single split within a withdrawal plan
#[derive(Clone, Copy, Default)]
pub struct SplitDetail {
    /// Destination wallet public key
    pub destination: [u8; 32],
    
    /// Amount in lamports for this split
    pub amount: u64,
    
    /// Delay in seconds from previous split (or from plan creation for first split)
    pub delay_seconds: u32,
    
    /// Scheduled execution timestamp (Unix)
    /// 0 means not yet scheduled
    pub scheduled_at: i64,
    
    /// Actual execution timestamp (Unix)
    /// 0 means not yet executed
    pub executed_at: i64,
    
    /// Transaction signature after execution
    /// All zeros if not yet executed
    pub tx_signature: [u8; 64],
}

/// Withdrawal execution plan generated by MPC
/// 
/// This plan contains the randomized split details for a withdrawal.
/// The randomization is performed within the MPC cluster using the
/// user's configured ranges and entropy provided at request time.
#[derive(Clone, Copy)]
pub struct WithdrawalPlan {
    /// Unique identifier for this plan
    pub plan_id: [u8; 16],
    
    /// Vault public key this plan is for
    pub vault_pubkey: [u8; 32],
    
    /// Total amount being withdrawn (lamports)
    pub total_amount: u64,
    
    /// Number of active splits in this plan
    pub split_count: u8,
    
    /// Individual split details (only first `split_count` are valid)
    pub splits: [SplitDetail; MAX_SPLITS],
    
    /// Unix timestamp when plan was created
    pub created_at: i64,
    
    /// Unix timestamp when plan expires (for security)
    /// Expired plans cannot be executed
    pub expires_at: i64,
    
    /// Number of splits already executed
    pub executed_count: u8,
    
    /// Plan status
    pub status: PlanStatus,
}

impl Default for WithdrawalPlan {
    fn default() -> Self {
        Self {
            plan_id: [0u8; 16],
            vault_pubkey: [0u8; 32],
            total_amount: 0,
            split_count: 0,
            splits: [SplitDetail::default(); MAX_SPLITS],
            created_at: 0,
            expires_at: 0,
            executed_count: 0,
            status: PlanStatus::Pending,
        }
    }
}

/// Status of a withdrawal plan
#[derive(Clone, Copy, PartialEq, Default)]
pub enum PlanStatus {
    /// Plan created but not started
    #[default]
    Pending,
    /// Plan execution in progress
    InProgress,
    /// All splits executed successfully
    Completed,
    /// Plan was cancelled by user
    Cancelled,
    /// Plan execution failed
    Failed,
    /// Plan expired before completion
    Expired,
}

/// Result of executing a single withdrawal split
#[derive(Clone, Copy)]
pub struct WithdrawalExecution {
    /// The destination wallet that received funds
    pub destination: [u8; 32],
    
    /// Amount transferred (lamports)
    pub amount: u64,
    
    /// Transaction signature
    pub tx_signature: [u8; 64],
    
    /// Execution timestamp
    pub executed_at: i64,
    
    /// Whether execution was successful
    pub success: bool,
    
    /// Error code if failed (0 = no error)
    pub error_code: u8,
}

/// Encrypted balance information
#[derive(Clone, Copy)]
pub struct BalanceInfo {
    /// Current vault balance (lamports)
    pub balance: u64,
    
    /// Pending withdrawal amount (lamports)
    pub pending_withdrawals: u64,
    
    /// Available balance (balance - pending)
    pub available: u64,
    
    /// Number of pending splits
    pub pending_split_count: u8,
    
    /// Timestamp of balance query
    pub queried_at: i64,
}

/// Updates to apply to private config
#[derive(Clone, Copy)]
pub struct ConfigUpdates {
    /// New destinations (if updating)
    pub new_destinations: Option<[[u8; 32]; MAX_DESTINATIONS]>,
    
    /// New destination count (if updating)
    pub new_destination_count: Option<u8>,
    
    /// New min splits (if updating)
    pub new_min_splits: Option<u8>,
    
    /// New max splits (if updating)
    pub new_max_splits: Option<u8>,
    
    /// New min delay (if updating)
    pub new_min_delay_seconds: Option<u32>,
    
    /// New max delay (if updating)
    pub new_max_delay_seconds: Option<u32>,
    
    /// New auto-withdraw setting (if updating)
    pub new_auto_withdraw_enabled: Option<bool>,
    
    /// New auto-withdraw threshold (if updating)
    pub new_auto_withdraw_threshold: Option<u64>,
}

impl Default for ConfigUpdates {
    fn default() -> Self {
        Self {
            new_destinations: None,
            new_destination_count: None,
            new_min_splits: None,
            new_max_splits: None,
            new_min_delay_seconds: None,
            new_max_delay_seconds: None,
            new_auto_withdraw_enabled: None,
            new_auto_withdraw_threshold: None,
        }
    }
}

/// Entropy input for randomization
/// 
/// Users provide this entropy to ensure randomization is unpredictable
/// even to the MPC cluster (combines with MPC-generated randomness)
#[derive(Clone, Copy)]
pub struct UserEntropy {
    /// Random bytes from user
    pub user_random: [u8; 32],
    
    /// Timestamp for freshness
    pub timestamp: i64,
    
    /// Signature proving user generated this entropy
    pub signature: [u8; 64],
}

